---
baseURL: "/manual/7.18/"
languageCode: "en-us"
title: "Camunda Platform 7 documentation"
theme: "camunda"

blackfriday:
  plainIDAnchors: true

params:
  canonicalBasePath: "https://docs.camunda.org"
  sections:
    - id: "get-started"
      name: "Get Started"
      url: "/get-started"
    - id: "manual"
      name: "Camunda Platform 7"
      url: "/manual"
    - id: "optimize"
      name: "Optimize"
      url: "/optimize"
    - id: 'cawemo'
      name: 'Cawemo'
      url: '/cawemo'
    - id: "enterprise"
      name: "Enterprise"
      url: "/enterprise"
    - id: "security"
      name: "Security"
      url: "/security"
  section:
    id: "manual"
    version: "7.18"
    versionAlias: "7.18"
    versions:
      - "latest"
      - "7.18"
      - "7.17"
      - "7.16"
      - "7.15"
      - "7.14"
      - "7.13"
      - "7.12"
      - "7.11"
      - "7.10"
      - "7.9"
      - "7.8"
      - "7.7"
      - "7.6"
      - "7.5"
      - "7.4"
      - "7.3"
      - "7.2"
      - "7.1"
      - "7.0"
      - "develop"
  github:
    repositoryName: "camunda/camunda-docs-manual"
    branch: "7.18"

outputs:
  home:
    - "HTML"
    - "RSS"
  section:
    - "HTML"

disableKinds:
- taxonomy
- taxonomyTerm
...
