---
baseurl: "/manual/7.7/"
languageCode: "en-us"
title: "Camunda BPM documentation"
theme: "camunda"

blackfriday:
  plainIDAnchors: true

params:
  sections:
    - id: "get-started"
      name: "Get Started"
      url: "/get-started"
    - id: "manual"
      name: "Manual"
      url: "/manual"
    - id: "enterprise"
      name: "Enterprise"
      url: "/enterprise"
  section:
    id: "manual"
    version: "7.7"
    versions:
      - "latest"
      - "7.7"
      - "7.6"
      - "7.5"
      - "7.4"
      - "7.3"
      - "7.2"
      - "7.1"
      - "7.0"
      - "develop"
  github:
    repositoryName: "camunda/camunda-docs-manual"
    branch: "7.7"
...
